name: documentroutingsystem
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.1.2       # Firestore integration
  intl: ^0.18.1                 # For DateFormat
  csv: ^5.0.0                   # CSV export
  pdf: ^3.11.3                  # PDF generation
  path_provider: ^2.0.15        # File system paths
  excel: ^4.0.3                  # Excel export
  flutter_switch: ^0.3.2        # Optional: nice toggle switch for light/dark mode
  file_picker: ^8.0.0+1         # File picker for attachments

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/company_logo.png
