// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPcFKZhU4Yx7uPIBFqMugu6FyWrkYJCls',
    appId: '1:1012540641487:web:e67a913f2c865bfa6027ba',
    messagingSenderId: '1012540641487',
    projectId: 'documentroutingsystemweb',
    authDomain: 'documentroutingsystemweb.firebaseapp.com',
    storageBucket: 'documentroutingsystemweb.firebasestorage.app',
    measurementId: 'G-JDTQWPSJ9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8iT3tqRRJ42EXJonybHwcKi3Y963qtsI',
    appId: '1:1012540641487:android:72d0307599800ad06027ba',
    messagingSenderId: '1012540641487',
    projectId: 'documentroutingsystemweb',
    storageBucket: 'documentroutingsystemweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4EJ8aONH3yJN-vVI2UYGtTlOpQjkUEo',
    appId: '1:1012540641487:ios:5e6a04ad2edc11e66027ba',
    messagingSenderId: '1012540641487',
    projectId: 'documentroutingsystemweb',
    storageBucket: 'documentroutingsystemweb.firebasestorage.app',
    iosBundleId: 'com.example.documentroutingsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx4EJ8aONH3yJN-vVI2UYGtTlOpQjkUEo',
    appId: '1:1012540641487:ios:5e6a04ad2edc11e66027ba',
    messagingSenderId: '1012540641487',
    projectId: 'documentroutingsystemweb',
    storageBucket: 'documentroutingsystemweb.firebasestorage.app',
    iosBundleId: 'com.example.documentroutingsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPcFKZhU4Yx7uPIBFqMugu6FyWrkYJCls',
    appId: '1:1012540641487:web:57b3491675e769266027ba',
    messagingSenderId: '1012540641487',
    projectId: 'documentroutingsystemweb',
    authDomain: 'documentroutingsystemweb.firebaseapp.com',
    storageBucket: 'documentroutingsystemweb.firebasestorage.app',
    measurementId: 'G-6BBC8F8BKH',
  );
}
